### ISSUE TITLE
venv test run failed

### ISSUE THREAD

**Issue by aracloud** [benmi3/gandi-ddns#1]
Hi

I just configured as explained via config.ini file but with the first run I got this traceback:

$ .venv/bin/python3 gandi-ddns.py
Traceback (most recent call last):
  File "gandi-ddns.py", line 37, in <module>
    def get_ip(record_type=str()) -> str | int:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

any clue what happened?

**Comment by benmi3** [comment]
Thank you for opening an issue, I'm looking into it! Could you please tell me what version of python you are running the script with? (.venv/bin/python3 --version)
And the version of dependencies? (.venv/bin/python3 -m pip list )

**Comment by aracloud** [comment]
$ .venv/bin/python3 --version
Python 3.7.3

$ .venv/bin/python3 -m pip list
Package            Version 
------------------ --------
certifi            2023.5.7
charset-normalizer 3.1.0   
idna               3.4     
pip                18.1    
pkg-resources      0.0.0   
requests           2.31.0  
setuptools         40.8.0  
urllib3            2.0.3

**Comment by aracloud** [comment]
I upgraded debian from 10 to 11.7

$ .venv/bin/python3 --version
Python 3.9.2
$ .venv/bin/python3 -m pip list
Package            Version
------------------ --------
certifi            2023.5.7
charset-normalizer 3.1.0
idna               3.4
pip                20.3.4
pkg-resources      0.0.0
requests           2.31.0
setuptools         44.1.1
urllib3            2.0.3


$ .venv/bin/python3 gandi-ddns.py
Traceback (most recent call last):
  File "/home/ndee/gitrepo/gandi-ddns/gandi-ddns.py", line 37, in <module>
    def get_ip(record_type=str()) -> str | int:
TypeError: unsupported operand type(s) for |: 'type' and 'type'

So, it remains the same...

**Comment by benmi3** [comment]
Hi, I believe the problem is the python version you are running, as I created it using python3.10. one of the features I used is not in the older versions, so I created a version of the script that doesn't use it. The script is called gandi-ddns-for-pre310.py.
This should fix your problem.

**Comment by aracloud** [comment]
I updated my debian to 12.0 and now it works with python 3.11.2. 
Thank you so much for your help and your effort with a pre 3.10 release !!!
